forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add_thread, name='add_thread'),
    path('<int:pk>/', views.thread_detail, name='detail_thread'),
    path('<int:pk>/edit/', views.edit_thread, name='edit_thread'),
    path('<int:pk>/reply/', views.reply_thread, name='reply_thread'),
    path('<int:pk>/delete/', views.delete_thread, name='delete_thread'),
]

hadirin/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('izin/', include('perizinan.urls')),
    path('forum/', include('forum.urls')),
    path('auth/', include('autentikasi.urls')),
    path('pengumuman/', include('pengumuman.urls')),
    path('role-divisi/', include('role_divisi.urls'))
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profil', views.profil, name='profil'),
    path('profil/edit', views.profil_edit, name='profil_edit'),
    path('presensi', views.presensi.as_view(), name='presensi'),
    path('presensi/add', views.presensi_edit, name='presensi_edit'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Thread(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    def __str__(self) -> str:
        return self.title


class ThreadReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    main_thread = models.ForeignKey(Thread, on_delete=models.CASCADE, related_name="replies")
    date_posted = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    def __str__(self) -> str:
        return f'Re: {self.main_thread.title}'

forum/forms.py
from django.forms import ModelForm
from .models import Thread, ThreadReply

class ThreadForm(ModelForm):
    class Meta:
        model = Thread
        fields = ['title', 'content']

class ThreadReplyForm(ModelForm):
    class Meta:
        model = ThreadReply
        fields = ['content']

forum/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from forum.forms import ThreadForm, ThreadReplyForm
from django.contrib.auth.decorators import login_required
from forum.models import Thread

@login_required
def home(request):
    threads = Thread.objects.all()
    return render(request, 'forum/index.html', { "threads": threads })

@login_required
def thread_detail(request, pk):
    thread = Thread.objects.get(id = pk)
    return render(request, 'forum/thread_detail.html', { "thread": thread })

@login_required
def add_thread(request):
    if request.method == 'POST':
        form = ThreadForm(request.POST)
        if form.is_valid():
            thread = form.save(commit=False)
            thread.user = request.user
            thread.save()
            messages.success(request, 'Thread berhasil dibuat')
            return redirect('forum:home')
        else:
            messages.error(request, form.errors)
    return render(request, 'forum/add_thread.html')

@login_required
def edit_thread(request, pk):
    thread = Thread.objects.get(id = pk)
    if request.user != thread.user:
        messages.error(request,'403: Access Denied')
        return redirect('forum:home')
    if request.method == 'POST':
        form = ThreadForm(request.POST, instance=thread)
        if form.is_valid():
            form.save()
            return redirect('forum:detail_thread', pk=pk)
        else:
            messages.error(request, form.errors)
    return render(request, 'forum/edit_thread.html', { 'thread' : thread })

@login_required
def reply_thread(request, pk):
    if request.method == "POST":
        form = ThreadReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.main_thread = Thread.objects.get(id = pk)
            reply.save()
            return redirect('forum:detail_thread', pk=pk)
        else:
            messages.error(request, form.errors)
    thread = Thread.objects.get(id = pk)
    return render(request, 'forum/reply_thread.html', { 'thread' : thread })

@login_required
def delete_thread(request, pk):
    thread = Thread.objects.get(id = pk)
    if request.user != thread.user:
        messages.error(request,'403: Access Denied')
        return redirect('forum:home')
    if request.method == 'POST':
        thread.delete()
        messages.success(request, 'Thread berhasil dihapus')
        return redirect('forum:home')
    return render(request, 'forum/delete_thread.html', { "thread" : thread })

forum/templates/forum/add_thread.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin - Add New Thread</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
	<div class="page-content">
		{% if messages %}
        {% for message in messages %}
        <div class="message-box {{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
		<h1 class="form-heading">Buat Thread baru</h1>
			<form class="form-box" action="{% url 'forum:add_thread' %}" method="POST">
				{% csrf_token %}
				<input type="hidden" name="user" value="{{thread.user.id}}">
				<div class="form-field">
					<label class="field-label">Judul</label>
					<input class="form-input" type="text" placeholder="Judul Topik" name="title" required>
				</div>
				<div class="form-field">
					<label class="field-label">Konten</label>
					<textarea class="form-input" placeholder="Konten" name="content" rows="7" required></textarea>
				</div>
				<div class="form-buttons">
					<a href="{% url 'forum:home' %}"><button type="button" class="button-outline">Batal</button></a>
					<button class="button-fill" type="submit">Simpan</button>
				</div>
		</div>
	</div>
</div>

{% endblock content %}

forum/templates/forum/delete_thread.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin - Delete Thread</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/delete_thread.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
	<div class="page-content">
		<form class="confirmation-box" action="{% url 'forum:delete_thread' thread.id %}" method="POST">
			{% csrf_token %}
			<div class="confirm-message">
				<div>Apakah anda yakin menghapus thread dengan judul</div>
				<div><strong>{{thread.title}}</strong>?</div>
			</div>
			<div class="form-buttons">
				<a href="{% url 'forum:detail_thread' thread.id %}"><button type="button" class="button-outline danger">Batal</button></a>
				<button class="button-fill danger" type="submit">Hapus</button>
			</div>
		</form>
	</div>
</div>
</div>

{% endblock content %}

forum/templates/forum/edit_thread.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin -Edit Thread</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
	<div class="page-content">
		{% if messages %}
        {% for message in messages %}
        <div class="message-box {{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
		<h1 class="form-heading">Ubah Thread</h1>
		<form class="form-box" action="{% url 'forum:edit_thread' thread.id %}" method="POST">
			{% csrf_token %}
			<div class="form-field">
				<label class="field-label">Judul</label>
				<input class="form-input" type="text" placeholder="Judul Topik" name="title" value="{{thread.title}}">
			</div>
			<div class="form-field">
				<label class="field-label">Konten</label>
				<textarea class="form-input" placeholder="Konten" name="content" value="{{thread.content}}"
					rows="10">{{thread.content}}</textarea>
			</div>
			<div class="form-buttons">
				<a href="{% url 'forum:detail_thread' thread.id %}"><button class="button-outline">Batal</button></a>
				<button class="button-fill" type="submit">Simpan</button>
			</div>
	</div>
</div>

{% endblock content %}

forum/templates/forum/index.html
{% extends 'base.html' %}
{% load tz %}
{% load static %}

{% block meta %}
<title>Hadirin - Forum</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
    <div class="page-content">
        {% if messages %}
        {% for message in messages %}
        <div class="message-box {{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="page-header">
            <h1>Forum</h1>
            <a class="button-fill" href="{% url 'forum:add_thread' %}">Buat Thread Baru</a>
        </div>
        <div class="threads">
            {% for thread in threads%}
            <div class="thread">
                <div class="thread-content">
                    <a href="{% url 'forum:detail_thread' thread.id %}">
                        <h2 class="thread-title">{{thread.title}}</h2>
                    </a>
                </div>
                <div class="thread-info">
                    <span class="thread-author">{{thread.user.username}}</span>
                    <span class="thread-postdate">{{thread.date_posted|localtime}}</span>
                </div>
                <a href="{% url 'forum:detail_thread' thread.id %}" class="thread-reply-count">
                    <img src="{% static 'img/ICON-reply.svg' %}" alt="">
                    <span>{{thread.replies.count}}</span>
                </a>
                
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

forum/templates/forum/reply_thread.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin - Reply Thread</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/thread_detail.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
	<div class="page-content">
		{% if messages %}
        {% for message in messages %}
        <div class="message-box {{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
		<div class="thread-detail">
			<h2 class="thread-title">{{thread.title}}</h2>
			<div class="thread-info">
				<span class="thread-author">{{thread.user}}</span>
				<span class="thread-postdate">{{thread.date_posted}}</span>
			</div>
			<p class="thread-message">
				{{thread.content}}
			</p>
		</div>
		<div class="thread-replies">
			<form class="reply-form" action="{% url 'forum:reply_thread' thread.id %}" method="POST">
				{% csrf_token %}
				<h2>Re: {{thread.title}}</h2>
				<textarea class="form-input" rows="10" placeholder="Tulis pesan" name="content"></textarea>
				<div class="reply-buttons">
					<a href="/forum/1/"><button type="button" class="button-outline">Batal</button></a>
					<button class="button-fill" type="submit">Kirim</button>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

forum/templates/forum/thread_detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin - Thread 1</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/thread_detail.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
	<div class="page-content">
		<div class="thread-detail">
			<h2 class="thread-title">{{thread.title}}</h2>
			<div class="thread-info">
				<span class="thread-author">{{thread.user.username}}</span>
				<span class="thread-postdate">{{thread.date_posted}}</span>
			</div>
			<p class="thread-message">
				{{thread.content}}
			</p>
			<div class="thread-buttons">
				{% if request.user == thread.user %}
				<a href="{% url 'forum:delete_thread' thread.id %}" class="action-button delete">Hapus</a>
				<a href="{% url 'forum:edit_thread' thread.id %}" class="action-button">Ubah</a>
				{% endif %}
				<a href="{% url 'forum:reply_thread' thread.id %}" class="action-button">Balas</a>
			</div>
		</div>
		<div class="thread-replies">
			{% for reply in thread.replies.all %}
			<div class="thread-reply">
				<div class="thread-info">
					<span class="thread-author">{{reply.user}}</span>
					<span class="thread-postdate">{{reply.date_posted}}</span>
				</div>
				<p class="thread-message">
					{{reply.content}}
				</p>
			</div>
			<!-- <div class="thread-reply">
				<div class="thread-info">
					<span class="thread-author">Rudi Rudiman</span>
					<span class="thread-postdate">November 28 2021, 9:01 PM</span>
				</div>
				<p class="thread-message">
					Saya tidak setuju
				</p>
			</div> -->
			{% endfor %}
		</div>
	</div>
</div>

{% endblock content %}