hadirin/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('izin/', include('perizinan.urls')),
    path('forum/', include('forum.urls')),
    path('auth/', include('autentikasi.urls')),
    path('pengumuman/', include('pengumuman.urls')),
    path('role-divisi/', include('role_divisi.urls'))
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profil', views.profil, name='profil'),
    path('profil/edit', views.profil_edit, name='profil_edit'),
    path('presensi', views.presensi.as_view(), name='presensi'),
    path('presensi/add', views.presensi_edit, name='presensi_edit'),
]

pengumuman/urls.py
from django.urls import path
from . import views

app_name = 'pengumuman'

urlpatterns = [
    path('', views.pengumuman, name='pengumuman'),
    path('pengumuman_saya/', views.pengumuman_saya, name='pengumuman_saya'),
    path('buat_pengumuman/', views.buat_pengumuman, name='buat_pengumuman'),
    path('edit_pengumuman/<int:id>', views.edit_pengumuman, name='edit_pengumuman'),
    path('hapus_pengumuman/<int:id>', views.hapus_pengumuman, name='hapus_pengumuman'),
]

pengumuman/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Pengumuman(models.Model):
    judul = models.CharField(max_length = 150)
    isi = models.TextField()
    user =  models.ForeignKey(User, on_delete = models.CASCADE)
    tanggal_post = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

pengumuman/forms.py
from django import forms
from .models import Pengumuman

class PengumumanForm(forms.ModelForm):
    class Meta:
        model = Pengumuman
        fields = ["judul", "isi"]
    
    error_messages = {
        'required' : 'Informasi Wajib Diisi'
    }
    
    input_attrs_judul = {
        'type' : 'text',
        'placeholder' : 'Judul Pengumuman',
        'class' : 'form-control',
        'autocomplete' : 'off',
        'required' : True
    }
    
    input_attrs_isi = {
        'type' : 'text',
        'placeholder' : 'Isi Pengumuman',
        'class' : 'form-control',
        'autocomplete' : 'off',
        'required' : True
    }
    
    judul = forms.CharField(label='Judul', max_length=150, widget=forms.TextInput(attrs=input_attrs_judul))
    isi = forms.CharField(label='Isi', widget=forms.Textarea(attrs=input_attrs_isi))

pengumuman/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render, get_object_or_404
from .forms import PengumumanForm
from .models import Pengumuman


# Create your views here.
context = {}

@login_required
def pengumuman(request):
    user = User.objects.get(id=request.user.id)
    pengumuman = Pengumuman.objects.order_by("-tanggal_post")
    context["pengumuman"] = pengumuman
    context["user"] = user
    if request.user.is_superuser:
        context["role"] = "admin"
    else:
        context["role"] = request.user.profile.role

    return render(request, 'pengumuman/pengumuman.html', context)

@login_required
def pengumuman_saya(request):
    if request.user.is_superuser or request.user.profile.role != "staf":
        user = User.objects.get(id = request.user.id)
        pengumuman = Pengumuman.objects.filter(user = user).order_by("-tanggal_post")
        context["pengumuman"] = pengumuman
        return render(request, 'pengumuman/pengumuman_saya.html', context)
    else:
        return redirect("main:home")

@login_required
def buat_pengumuman(request):
    if request.user.is_superuser or request.user.profile.role != "staf":
        context["form"] = PengumumanForm()
        if request.method == 'POST':
            user = User.objects.get(id = request.user.id)
            form = PengumumanForm(request.POST or None)
            if request.POST and form.is_valid():
                judul = form.cleaned_data['judul']
                isi = form.cleaned_data['isi']
                pengumuman = Pengumuman.objects.create(judul = judul, isi = isi, user=user)
                messages.success(request, 'Pengumuman berhasil dibuat!')
                return redirect('pengumuman:pengumuman_saya')
            else:
                messages.error(request, 'Form tidak berhasil dibuat!')
                return redirect("pengumuman:buat_pengumuman")
        return render(request, 'pengumuman/buat_pengumuman.html', context)
    else:
        return redirect("main:home")

@login_required
def edit_pengumuman(request, id):
    if request.user.is_superuser or request.user.profile.role != "staf":
        context["id"] = id
        pengumuman = get_object_or_404(Pengumuman, id=id)
        if request.method == 'POST':
            form = PengumumanForm(request.POST or None, instance = pengumuman)
            user = User.objects.get(id = request.user.id)
            if request.POST and form.is_valid():
                judul = form.cleaned_data['judul']
                isi = form.cleaned_data['isi']
                pengumuman = Pengumuman.objects.filter(id=id).update(judul=judul, isi=isi)
                messages.success(request, 'Pengumuman berhasil diubah!')
                return redirect('pengumuman:pengumuman_saya')
            else:
                messages.error(request, 'Form tidak berhasil dibuat!')
                return redirect("pengumuman:buat_pengumuman")

        judul = pengumuman.judul
        isi = pengumuman.isi
        pengumuman_form = PengumumanForm(request.POST)
        pengumuman_form.fields["judul"].widget.attrs["value"] = judul
        pengumuman_form.fields["isi"].widget.attrs["value"] = isi
        context["form"] = pengumuman_form
        return render(request, 'pengumuman/edit_pengumuman.html', context)

    else:
        return redirect("main:home")

@login_required
def hapus_pengumuman(request, id):
    if request.user.is_superuser or request.user.profile.role != "staf":
        pengumuman = get_object_or_404(Pengumuman, id=id)
        context["id"] = id
        if request.method == 'POST':
            pengumuman.delete()
            messages.success(request, 'Pengumuman berhasil dihapus!')
            return redirect('pengumuman:pengumuman_saya')
        return render(request, 'pengumuman/hapus_pengumuman.html', context)

    else:
        return redirect("main:home")

pengumuman/templates/pengumuman/buat_pengumuman.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin - Buat Pengumuman</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/pengumuman.css' %}">
<link rel="stylesheet" href="{% static 'css/buat_pengumuman.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
    <div class="confirmation-title">
		<div><strong>Buat Pengumuman</strong></div>
	</div>
	{% if messages %}
	{% for message in messages %}
	<div class="message-box {{ message.tags }}">
		{{ message }}
	</div>
	{% endfor %}
	{% endif %}
	<div class="page-content">

			<form class="form-box" action="{% url 'pengumuman:buat_pengumuman' %}" method="POST">
                {% csrf_token %}
				<div class="form-field">
					<label class="field-label">Judul</label>
					{{ form.judul }}
				</div>
				<div class="form-field">
					<label class="field-label">Isi</label>
					{{ form.isi }}
				</div>
				<div class="form-buttons">
					<a href="{% url 'pengumuman:pengumuman_saya' %}"><button type="button" class="button-outline">Batal</button></a>
					<a href="{% url 'pengumuman:pengumuman_saya' %}"><button class="button-fill" type="submit">Simpan</button></a>
				</div>
            </form>
	</div>
</div>

{% endblock content %}

pengumuman/templates/pengumuman/edit_pengumuman.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin - Edit Pengumuman</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/pengumuman.css' %}">
<link rel="stylesheet" href="{% static 'css/edit_pengumuman.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
    <div class="confirmation-title">
		<div><strong>Edit Pengumuman</strong></div>
	</div>
	{% if messages %}
	{% for message in messages %}
	<div class="message-box {{ message.tags }}">
		{{ message }}
	</div>
	{% endfor %}
	{% endif %}
	<div class="page-content">
			<form class="form-box" action="{% url 'pengumuman:edit_pengumuman' id=id %}" method="POST">
                {% csrf_token %}
				<div class="form-field">
					<label class="field-label">Judul</label>
					{{ form.judul }}
				</div>
				<div class="form-field">
					<label class="field-label">Isi</label>
					{{ form.isi }}
				</div>
				<div class="form-buttons">
					<a href="{% url 'pengumuman:pengumuman_saya' %}"><button type="button" class="button-outline">Batal</button></a>
					<a href="{% url 'pengumuman:pengumuman_saya' %}"><button class="button-fill" type="submit">Ubah</button></a>
				</div>
            </form>
	</div>
</div>

{% endblock content %}

pengumuman/templates/pengumuman/hapus_pengumuman.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin - Hapus Pengumuman</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/hapus_pengumuman.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
	<div class="confirmation-title">
		<div><strong>Hapus Pengumuman</strong></div>
	</div>
	{% if messages %}
	{% for message in messages %}
	<div class="message-box {{ message.tags }}">
		{{ message }}
	</div>
	{% endfor %}
	{% endif %}
	<div class="page-content">
		<form class="confirmation-box" action="{% url 'pengumuman:hapus_pengumuman' id=id%}" method="POST">
			{% csrf_token %}
			<div class="confirm-message">
				<div><strong>Apakah anda yakin menghapus pengumuman ini?</strong></div>
			</div>
			<div class="form-buttons">
				<a href="{% url 'pengumuman:pengumuman_saya' %}"><button type="button" class="button-outline danger">Batal</button></a>
				<a href="{% url 'pengumuman:pengumuman_saya' %}"><button class="button-fill danger" type="submit">Hapus</button></a>
			</div>
		</form>
	</div>
</div>
</div>

{% endblock content %}

pengumuman/templates/pengumuman/pengumuman.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin - Pengumuman</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/pengumuman.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
    <div class="page-content">
        <div class="page-header">
            <h1>Pengumuman</h1>
            {% if role != "staf" %}
            <a class="button-fill" href="{% url 'pengumuman:pengumuman_saya' %}">Pengumuman Saya</a>
            {% endif %}
        </div>
        <div class="lst-pengumuman">
            {% for isi in pengumuman %}
            <div class="pengumuman">
                <div class="pengumuman-konten">
                    <a><h2 class="pengumuman-title"><strong>{{ isi.judul }}</strong></h2></a>
                    <a>{{ isi.isi }}</a>
                </div>
                <div class="pengumuman-footer">
                    <span class="pengumuman-author">{{ isi.user }}</span>
                    <span class="pengumuman-postdate">{{ isi.tanggal_post }}</span>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

pengumuman/templates/pengumuman/pengumuman_saya.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hadirin - Pengumuman Saya</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/pengumuman.css' %}">
{% endblock meta %}

{% block content %}
<div class="page-container">
    {% if messages %}
    {% for message in messages %}
    <div class="message-box {{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="page-content">
        <div class="page-header">
            <h1>Pengumuman Saya</h1>
            <div class="pengumuman-buttons">
                <a class="button-fill" href="{% url 'pengumuman:pengumuman' %}">Kembali</a>
                <a class="button-fill" href="{% url 'pengumuman:buat_pengumuman' %}">Buat Pengumuman</a>
            </div>
        </div>
        <div class="lst-pengumuman">

            {% for isi in pengumuman %}
            <div class="pengumuman">
                <div class="pengumuman-konten">
                    <a><h2 class="pengumuman-title"><strong>{{ isi.judul }}</strong></h2></a>
                    <a>{{ isi.isi }}</a>
                </div>
                <div class="pengumuman-footer">
                    <span class="pengumuman-author">{{ isi.user }}</span>
                    <span class="pengumuman-postdate">{{ isi.tanggal_post }}</span>
                    <div class="pengumuman-buttons">
                        <a href="{% url 'pengumuman:hapus_pengumuman' id=isi.id %}" class="action-button delete">Hapus</a>
                        <a href="{% url 'pengumuman:edit_pengumuman' id=isi.id %}" class="action-button">Edit</a>
                    </div>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}