autentikasi/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'autentikasi'

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name = "autentikasi/login.html"), name='login'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view , name="logout"),
    path('register/', views.register, name='register'),
] 

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add_thread, name='add_thread'),
    path('<int:pk>/', views.thread_detail, name='detail_thread'),
    path('<int:pk>/edit/', views.edit_thread, name='edit_thread'),
    path('<int:pk>/reply/', views.reply_thread, name='reply_thread'),
    path('<int:pk>/delete/', views.delete_thread, name='delete_thread'),
]

hadirin/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('izin/', include('perizinan.urls')),
    path('forum/', include('forum.urls')),
    path('auth/', include('autentikasi.urls')),
    path('pengumuman/', include('pengumuman.urls')),
    path('role-divisi/', include('role_divisi.urls'))
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profil', views.profil, name='profil'),
    path('profil/edit', views.profil_edit, name='profil_edit'),
    path('presensi', views.presensi.as_view(), name='presensi'),
    path('presensi/add', views.presensi_edit, name='presensi_edit'),
]

pengumuman/urls.py
from django.urls import path
from . import views

app_name = 'pengumuman'

urlpatterns = [
    path('', views.pengumuman, name='pengumuman'),
    path('pengumuman_saya/', views.pengumuman_saya, name='pengumuman_saya'),
    path('buat_pengumuman/', views.buat_pengumuman, name='buat_pengumuman'),
    path('edit_pengumuman/<int:id>', views.edit_pengumuman, name='edit_pengumuman'),
    path('hapus_pengumuman/<int:id>', views.hapus_pengumuman, name='hapus_pengumuman'),
]

perizinan/urls.py
from django.urls import path
from . import views

app_name = 'perizinan'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add_izin, name='add_izin'),
    path('detail/<int:id>', views.detail_izin, name='detail_izin'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    {% block meta %} {% endblock meta %}
  </head>
  <body>
    <nav class="navbar">
      <a href="/" class="nav-brand">Hadirin</a>
      <ul class="nav-links">
        {% if  user.is_superuser %}
        <li><a href="{% url 'role_divisi:role_divisi_list' %}">Divisi</a></li>
        <li><a href="{% url 'autentikasi:register' %}">Registrasi Akun</a></li>
        {% else %}
        <li><a href="/presensi">Presensi</a></li>
        <li><a href="{% url 'perizinan:index' %}">Perizinan</a></li>
        <li><a href="{% url 'forum:home' %}">Forum</a></li>
        {% endif %}
        <li><a href="{% url 'pengumuman:pengumuman' %}">Pengumuman</a></li>
        <div class="nav-profile" tabindex="-1">
          <button type="button" id="dropdown-button">
            <img class="icon-user" src="{% static 'img/ICON-profile.svg' %}" alt="profile">
          </button>
          <div class="dropdown-items">
            {% if user.is_authenticated %}
            <a class="dropdown-item" href="/profil">Profile</a>
            <a class="dropdown-item" href="{% url 'autentikasi:logout' %}">Logout</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'autentikasi:logout' %}">Login</a>
            {% endif %}
          </div>
        </div>
      </div>
    </ul>
  </nav>
  <div style="margin-top: 64px">
    {% block content %} {% endblock content %}
  </div>
  <script src="{% static 'js/navbar.js' %}"></script>
</body>

</html>