hadirin/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('izin/', include('perizinan.urls')),
    path('forum/', include('forum.urls')),
    path('auth/', include('autentikasi.urls')),
    path('pengumuman/', include('pengumuman.urls')),
    path('role-divisi/', include('role_divisi.urls'))
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profil', views.profil, name='profil'),
    path('profil/edit', views.profil_edit, name='profil_edit'),
    path('presensi', views.presensi.as_view(), name='presensi'),
    path('presensi/add', views.presensi_edit, name='presensi_edit'),
]

role_divisi/urls.py
from django.urls import path
from .views import IndexView, DetailRoleDivisiView, AddRoleDivisiView, EditRoleDivisiView, DeleteRoleDivisiView

app_name = 'role_divisi'

urlpatterns = [
    path('', IndexView.as_view(), name='role_divisi_list'),
    path('<int:pk>/', DetailRoleDivisiView.as_view(), name='detail_role_divisi'),
    path('tambah/', AddRoleDivisiView.as_view(), name='add_role_divisi'),
    path('ubah/<int:pk>/', EditRoleDivisiView.as_view(), name='edit_role_divisi'),
    path('hapus/<int:pk>/', DeleteRoleDivisiView.as_view(), name='delete_role_divisi')
]

role_divisi/models.py
from django.db import models

class RoleDivisi(models.Model):
    nama = models.CharField(max_length=50)
    keterangan = models.TextField()

    class Meta:
        db_table = 'role_divisi'

    def __str__(self):
        return self.nama

role_divisi/forms.py
from django.forms import ModelForm
from .models import RoleDivisi


class RoleDivisiForm(ModelForm):
    class Meta:
        model = RoleDivisi
        fields = '__all__'

role_divisi/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import RoleDivisi
from django.urls import reverse_lazy
from django.shortcuts import redirect


class BaseRoleDivisiView(LoginRequiredMixin, UserPassesTestMixin):
    model = RoleDivisi
    fields = '__all__'
    context_object_name = "role_divisi"

    def test_func(self):
        return self.request.user.is_superuser

    def get_permission_denied_message(self):
        return f"User {self.request.user} bukan seorang admin"

    def handle_no_permission(self):
        return redirect('main:home')


class IndexView(BaseRoleDivisiView, ListView):
    context_object_name = 'role_divisi_list'
    template_name = "role_divisi/index.html"


class DetailRoleDivisiView(BaseRoleDivisiView, DetailView):
    template_name = "role_divisi/detail.html"


class AddRoleDivisiView(BaseRoleDivisiView, CreateView):
    template_name = "role_divisi/add_form.html"

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, f"Role Divisi {self.object.nama} berhasil ditambahkan!")
        return reverse_lazy("role_divisi:role_divisi_list")


class EditRoleDivisiView(BaseRoleDivisiView, UpdateView):
    template_name = "role_divisi/edit_form.html"

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, f"Role Divisi {self.object.nama} berhasil diubah!")
        return reverse_lazy("role_divisi:role_divisi_list")


class DeleteRoleDivisiView(BaseRoleDivisiView, DeleteView):
    template_name = "role_divisi/confirm_delete.html"

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, f"Role Divisi {self.object.nama} berhasil dihapus!")
        return reverse_lazy("role_divisi:role_divisi_list")

role_divisi/templates/role_divisi/add_form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Hadirin - Tambah Role Divisi</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'role_divisi/css/index.css' %}">
{% endblock meta %}

{% block content %}
    <div class="container mx-auto flex flex-col page-content">
        <p class="font-bold text-2xl">Tambah Role Divisi</p>
        <form method="post" class="border-2 rounded-md p-6 flex flex-col">
            {% csrf_token %}
            {{ form.non_field_errors }}

            {% for field in form %}
                {{ field.errors }}
                <div class="flex flex-col space-y-2 mb-4">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                <span>{{ field.help_text }}</span>
            {% endfor %}
            <div class="flex space-x-4 items-center justify-center mt-16">
				<a href="{% url 'role_divisi:role_divisi_list' %}" class="button-outline">Batal</a>
                <button class="button-fill" type="submit">Simpan</button>
            </div>
        </form>
    </div>
{% endblock content %}

role_divisi/templates/role_divisi/confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Hadirin - Delete Role Divisi</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/delete_thread.css' %}">
{% endblock meta %}

{% block content %}
    <div class="container mx-auto page-content">
        <form method="post" class="confirmation-box">
            {% csrf_token %}
            <div class="confirm-message">
                <div>Apakah anda yakin menghapus role divisi ini ?</div>
            </div>
            <div class="form-buttons">
                <a href="{% url 'role_divisi:role_divisi_list' %}">
                    <button type="button" class="button-outline danger">Batal</button>
                </a>
                <button class="button-fill danger" type="submit">Hapus</button>
            </div>
        </form>
    </div>
{% endblock content %}

role_divisi/templates/role_divisi/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Hadirin - Detail Role Divisi</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock meta %}

{% block content %}
    <div class="container page-content mx-auto flex flex-col">
        <p class="font-bold text-2xl">Detail Role Divisi</p>
        <div class="border-2 rounded-md p-6">
            <div class="flex flex-col space-y-2 mb-4">
                <p class="font-bold">Nama</p>
                <p>{{ role_divisi.nama }}</p>
            </div>
            <div class="flex flex-col space-y-2">
                <p class="font-bold">Keterangan</p>
                <p>{{ role_divisi.keterangan }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

role_divisi/templates/role_divisi/edit_form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Hadirin - Ubah Role Divisi</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'role_divisi/css/index.css' %}"
{% endblock meta %}

{% block content %}
    <div class="container page-content mx-auto flex flex-col">
        <p class="font-bold text-2xl">Ubah Role Divisi</p>
        <form class="border-2 rounded-md p-6" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}

            {% for field in form %}
                {{ field.errors }}
                <div class="flex flex-col space-y-2 mb-4">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                <span>{{ field.help_text }}</span>
            {% endfor %}

            <div class="flex space-x-4 items-center justify-center">
				<a href="{% url 'role_divisi:role_divisi_list' %}" class="button-outline">Batal</a>
                <button class="button-fill" type="submit">Simpan</button>
            </div>
        </form>
    </div>
{% endblock content %}

role_divisi/templates/role_divisi/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Hadirin - Role Divisi</title>
    <link rel="stylesheet" href="{% static 'role_divisi/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock meta %}

{% block content %}
    <div class="page-content container mx-auto flex flex-col space-y-6">
        {% if messages %}
            {% for message in messages %}
                <div class="message-box {{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="flex space-between items-center justify-between">
            <p class="font-bold text-xl">Role Divisi</p>
            <a href="{% url 'role_divisi:add_role_divisi' %}">
                <button class="font-bold rounded text-lg py-2 px-5 text-white">Tambah Role Divisi</button>
            </a>
        </div>

        {% for role_divisi in role_divisi_list %}
            <div class="flex flex-col space-y-4">
                <div class="rounded-lg border-2 px-10 py-4 flex justify-between items-center">
					<p class="text-lg font-bold">{{ role_divisi.nama }}</p>
                    <div class="flex space-x-4 items-center">
                        <a href="{% url 'role_divisi:detail_role_divisi' role_divisi.id %}">Detail</a>
                        <a href="{% url 'role_divisi:edit_role_divisi' role_divisi.id %}">Ubah</a>
                        <a href="{% url 'role_divisi:delete_role_divisi' role_divisi.id %}" class="delete">Hapus</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}